name: tests-boa

on: [push]

env:
  DRPC_API_KEY: ${{ secrets.DRPC_API_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  
jobs:
  tests:
    runs-on: ubuntu-latest
    environment: env
    strategy:
      matrix:
        folder:
          - "tests/unitary"
          - "tests/integration"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.18"
          enable-cache: true  # Enables built-in caching for uv

      - name: Cache Compiler Installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.vvm
          key: compiler-cache-${{ hashFiles('**/uv.lock') }}

      - name: Set up Python 3.12.6
        run: uv python install 3.12.6

      - name: Install Requirements
        run: uv sync --extra=dev

      - name: Run tests in ${{ matrix.folder }}
        run: uv run pytest ${{ matrix.folder }}